# .github/workflows/metrics.yml
name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  profile-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate profile metrics SVG
        uses: lowlighter/metrics@v3.34
        with:
          user: ${{ github.repository_owner }}
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          output_action: skip-if-only-metadata-changed
          config_timezone: Europe/Amsterdam
          config_twemoji: yes
          base: header, activity, community, repositories, metadata
          template: classic

          # Keep only plugins that are safe right now
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_topics: yes
          plugin_habits: yes
          plugin_notable: yes

          # TEMP: achievements disabled due to Projects Classic breakage
          plugin_achievements: no
